// LocalStorage wrapper for game data

const STORAGE_KEYS = {
    QUESTIONS: 'tet_game_questions',
    USED_QR_CODES: 'tet_game_used_qr',
    GAME_STATE: 'tet_game_state',
    LEADERBOARD: 'tet_game_leaderboard',
    QR_CODES: 'tet_game_qr_codes',
    COMPANIES: 'tet_game_companies',
    CONFIG: 'tet_game_config',
};

// Questions
export const getQuestions = () => {
    const data = localStorage.getItem(STORAGE_KEYS.QUESTIONS);
    return data ? JSON.parse(data) : null;
};

export const saveQuestions = (questions) => {
    localStorage.setItem(STORAGE_KEYS.QUESTIONS, JSON.stringify(questions));
};

export const updateQuestionPriority = (questionId, decrease = true) => {
    const questions = getQuestions();
    if (questions) {
        const question = questions.find(q => q.id === questionId);
        if (question) {
            question.priority = decrease
                ? Math.max(1, question.priority - 1)
                : question.priority + 1;
            saveQuestions(questions);
        }
    }
};

// Used QR Codes
export const getUsedQRCodes = () => {
    const data = localStorage.getItem(STORAGE_KEYS.USED_QR_CODES);
    return data ? JSON.parse(data) : [];
};

export const markQRCodeUsed = (qrId) => {
    const usedCodes = getUsedQRCodes();
    if (!usedCodes.includes(qrId)) {
        usedCodes.push(qrId);
        localStorage.setItem(STORAGE_KEYS.USED_QR_CODES, JSON.stringify(usedCodes));
    }
};

export const isQRCodeUsed = (qrId) => {
    const usedCodes = getUsedQRCodes();
    return usedCodes.includes(qrId);
};

// Game State (per company)
export const getGameState = (companyId) => {
    const data = localStorage.getItem(`${STORAGE_KEYS.GAME_STATE}_${companyId}`);
    return data ? JSON.parse(data) : {
        companyId,
        revealedPieces: [],
        startTime: null,
        endTime: null,
        completed: false,
    };
};

export const saveGameState = (companyId, state) => {
    localStorage.setItem(`${STORAGE_KEYS.GAME_STATE}_${companyId}`, JSON.stringify(state));
};

export const revealPiece = (companyId, pieceIndex) => {
    const state = getGameState(companyId);
    if (!state.revealedPieces.includes(pieceIndex)) {
        state.revealedPieces.push(pieceIndex);
        if (!state.startTime) {
            state.startTime = Date.now();
        }
        saveGameState(companyId, state);
    }
    return state;
};

export const completeGame = (companyId) => {
    const state = getGameState(companyId);
    state.endTime = Date.now();
    state.completed = true;
    saveGameState(companyId, state);
    return state;
};

// Leaderboard
export const getLeaderboard = () => {
    const data = localStorage.getItem(STORAGE_KEYS.LEADERBOARD);
    return data ? JSON.parse(data) : [];
};

export const addToLeaderboard = (entry) => {
    const leaderboard = getLeaderboard();

    // Get current datetime
    const now = new Date();
    const completedAt = now.toLocaleString('vi-VN', {
        year: 'numeric',
        month: '2-digit',
        day: '2-digit',
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit'
    });

    leaderboard.push({
        ...entry,
        completedAt: completedAt,
        timestamp: Date.now(),
    });

    // Sort by timestamp (newest first)
    leaderboard.sort((a, b) => b.timestamp - a.timestamp);
    localStorage.setItem(STORAGE_KEYS.LEADERBOARD, JSON.stringify(leaderboard));
    return leaderboard;
};

// QR Codes (generated by admin)
export const getQRCodes = () => {
    const data = localStorage.getItem(STORAGE_KEYS.QR_CODES);
    return data ? JSON.parse(data) : [];
};

export const saveQRCodes = (codes) => {
    localStorage.setItem(STORAGE_KEYS.QR_CODES, JSON.stringify(codes));
};

// Companies
export const getCompanies = () => {
    const data = localStorage.getItem(STORAGE_KEYS.COMPANIES);
    return data ? JSON.parse(data) : null;
};

export const saveCompanies = (companies) => {
    localStorage.setItem(STORAGE_KEYS.COMPANIES, JSON.stringify(companies));
};

// Grid Config
export const getGridSize = () => {
    const data = localStorage.getItem(STORAGE_KEYS.CONFIG);
    if (data) {
        const config = JSON.parse(data);
        return config.gridSize || 3;
    }
    return 3;
};

export const saveGridSize = (size) => {
    const data = localStorage.getItem(STORAGE_KEYS.CONFIG);
    const config = data ? JSON.parse(data) : {};
    config.gridSize = size;
    localStorage.setItem(STORAGE_KEYS.CONFIG, JSON.stringify(config));
};

// Clear all game data
export const clearAllData = () => {
    Object.values(STORAGE_KEYS).forEach(key => {
        localStorage.removeItem(key);
    });
};

// Reset game results only (keep questions, QR codes, AND used QR status)
export const resetGameResults = () => {
    // Clear leaderboard
    localStorage.removeItem(STORAGE_KEYS.LEADERBOARD);

    // KHÔNG xóa used QR codes - giữ nguyên để QR đã dùng không thể quét lại
    // localStorage.removeItem(STORAGE_KEYS.USED_QR_CODES);

    // Reset all company game states by scanning all localStorage keys
    const gameStatePrefix = STORAGE_KEYS.GAME_STATE + '_';
    const keysToRemove = [];

    for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        if (key && key.startsWith(gameStatePrefix)) {
            keysToRemove.push(key);
        }
    }

    keysToRemove.forEach(key => {
        localStorage.removeItem(key);
    });
};

// Clear all QR codes
export const clearAllQRCodes = () => {
    localStorage.removeItem(STORAGE_KEYS.QR_CODES);
    localStorage.removeItem(STORAGE_KEYS.USED_QR_CODES);
};

// Clear used QR codes (mark all as unused)
export const clearUsedQRCodes = () => {
    localStorage.removeItem(STORAGE_KEYS.USED_QR_CODES);
};

// Export completion times as JSON backup
export const exportBackup = () => {
    const leaderboard = getLeaderboard();

    const backup = {
        exportedAt: new Date().toLocaleString('vi-VN'),
        timestamp: Date.now(),
        title: 'Kết quả hoàn thành Logo Game',
        completions: leaderboard.map(entry => ({
            companyName: entry.companyName,
            completedAt: entry.completedAt,
            timestamp: entry.timestamp
        }))
    };

    return backup;
};

// Download backup as JSON file
export const downloadBackup = () => {
    const backup = exportBackup();
    const fileName = `game_backup_${new Date().toISOString().slice(0, 10)}.json`;

    const blob = new Blob([JSON.stringify(backup, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    return fileName;
};

export default {
    getQuestions,
    saveQuestions,
    updateQuestionPriority,
    getUsedQRCodes,
    markQRCodeUsed,
    isQRCodeUsed,
    getGameState,
    saveGameState,
    revealPiece,
    completeGame,
    getLeaderboard,
    addToLeaderboard,
    getQRCodes,
    saveQRCodes,
    getCompanies,
    saveCompanies,
    getGridSize,
    saveGridSize,
    clearAllData,
    resetGameResults,
    clearAllQRCodes,
    clearUsedQRCodes,
    exportBackup,
    downloadBackup,
};
